# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Coding\Python\DesuraTools\qtui\mainform.ui'
#
# Created: Wed Nov 06 17:15:07 2013
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(527, 503)
        MainWindow.setToolTip("")
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.accountNameContainer = QtGui.QHBoxLayout()
        self.accountNameContainer.setObjectName("accountNameContainer")
        self.desuraAccountName_label = QtGui.QLabel(self.centralwidget)
        self.desuraAccountName_label.setObjectName("desuraAccountName_label")
        self.accountNameContainer.addWidget(self.desuraAccountName_label)
        self.desuraAccountName_input = QtGui.QLineEdit(self.centralwidget)
        self.desuraAccountName_input.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.desuraAccountName_input.setObjectName("desuraAccountName_input")
        self.accountNameContainer.addWidget(self.desuraAccountName_input)
        self.desuraAccountName_verify = QtGui.QPushButton(self.centralwidget)
        self.desuraAccountName_verify.setObjectName("desuraAccountName_verify")
        self.accountNameContainer.addWidget(self.desuraAccountName_verify)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.accountNameContainer.addWidget(self.line_2)
        self.steamID_label = QtGui.QLabel(self.centralwidget)
        self.steamID_label.setObjectName("steamID_label")
        self.accountNameContainer.addWidget(self.steamID_label)
        self.steamID_input = QtGui.QComboBox(self.centralwidget)
        self.steamID_input.setMinimumSize(QtCore.QSize(130, 0))
        self.steamID_input.setObjectName("steamID_input")
        self.accountNameContainer.addWidget(self.steamID_input)
        self.verticalLayout_2.addLayout(self.accountNameContainer)
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.installGamesTab = QtGui.QWidget()
        self.installGamesTab.setObjectName("installGamesTab")
        self.gridLayout_4 = QtGui.QGridLayout(self.installGamesTab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.installGames_list = QtGui.QListWidget(self.installGamesTab)
        self.installGames_list.setObjectName("installGames_list")
        self.gridLayout_4.addWidget(self.installGames_list, 0, 0, 1, 1)
        self.tabWidget.addTab(self.installGamesTab, "")
        self.addToSteam_tab = QtGui.QWidget()
        self.addToSteam_tab.setObjectName("addToSteam_tab")
        self.gridLayout_5 = QtGui.QGridLayout(self.addToSteam_tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.addToSteam_list = QtGui.QListWidget(self.addToSteam_tab)
        self.addToSteam_list.setObjectName("addToSteam_list")
        self.gridLayout_5.addWidget(self.addToSteam_list, 0, 0, 1, 1)
        self.tabWidget.addTab(self.addToSteam_tab, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.gameInfoContainer = QtGui.QHBoxLayout()
        self.gameInfoContainer.setObjectName("gameInfoContainer")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gameInfoContainer.addLayout(self.verticalLayout)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gameInfoContainer.addItem(spacerItem)
        self.desuraButton = QtGui.QPushButton(self.centralwidget)
        self.desuraButton.setObjectName("desuraButton")
        self.gameInfoContainer.addWidget(self.desuraButton)
        self.installButton = QtGui.QPushButton(self.centralwidget)
        self.installButton.setObjectName("installButton")
        self.gameInfoContainer.addWidget(self.installButton)
        self.verticalLayout_2.addLayout(self.gameInfoContainer)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 527, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionAdd_Selected_to_Steam = QtGui.QAction(MainWindow)
        self.actionAdd_Selected_to_Steam.setObjectName("actionAdd_Selected_to_Steam")
        self.generateDesuraReport_action = QtGui.QAction(MainWindow)
        self.generateDesuraReport_action.setObjectName("generateDesuraReport_action")
        self.menuFile.addAction(self.generateDesuraReport_action)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "DesuraTools", None, QtGui.QApplication.UnicodeUTF8))
        self.desuraAccountName_label.setText(QtGui.QApplication.translate("MainWindow", "Desura Account Name", None, QtGui.QApplication.UnicodeUTF8))
        self.desuraAccountName_input.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Your Desura Username", None, QtGui.QApplication.UnicodeUTF8))
        self.desuraAccountName_verify.setText(QtGui.QApplication.translate("MainWindow", "Verify Account", None, QtGui.QApplication.UnicodeUTF8))
        self.steamID_label.setText(QtGui.QApplication.translate("MainWindow", "Steam ID", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.installGamesTab), QtGui.QApplication.translate("MainWindow", "Owned Desura Games", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.addToSteam_tab), QtGui.QApplication.translate("MainWindow", "Installed Desura Games", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "GameIcon", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "GameName", None, QtGui.QApplication.UnicodeUTF8))
        self.desuraButton.setText(QtGui.QApplication.translate("MainWindow", "Desura Page", None, QtGui.QApplication.UnicodeUTF8))
        self.installButton.setText(QtGui.QApplication.translate("MainWindow", "Install", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdd_Selected_to_Steam.setText(QtGui.QApplication.translate("MainWindow", "Install Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.generateDesuraReport_action.setText(QtGui.QApplication.translate("MainWindow", "Generate Desura Report", None, QtGui.QApplication.UnicodeUTF8))

