# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Coding\Python\DesuraTools\ui\mainform.ui'
#
# Created: Fri Dec 13 06:09:30 2013
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(527, 503)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("desuratools_256.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolTip("")
        MainWindow.setIconSize(QtCore.QSize(256, 256))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.accountNameContainer = QtGui.QHBoxLayout()
        self.accountNameContainer.setObjectName("accountNameContainer")
        self.desuraAccountName_label = QtGui.QLabel(self.centralwidget)
        self.desuraAccountName_label.setObjectName("desuraAccountName_label")
        self.accountNameContainer.addWidget(self.desuraAccountName_label)
        self.desuraAccountName_input = QtGui.QLineEdit(self.centralwidget)
        self.desuraAccountName_input.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.desuraAccountName_input.setObjectName("desuraAccountName_input")
        self.accountNameContainer.addWidget(self.desuraAccountName_input)
        self.desuraAccountName_verify = QtGui.QPushButton(self.centralwidget)
        self.desuraAccountName_verify.setObjectName("desuraAccountName_verify")
        self.accountNameContainer.addWidget(self.desuraAccountName_verify)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.accountNameContainer.addWidget(self.line_2)
        self.steamID_label = QtGui.QLabel(self.centralwidget)
        self.steamID_label.setObjectName("steamID_label")
        self.accountNameContainer.addWidget(self.steamID_label)
        self.steamID_input = QtGui.QComboBox(self.centralwidget)
        self.steamID_input.setMinimumSize(QtCore.QSize(130, 0))
        self.steamID_input.setObjectName("steamID_input")
        self.accountNameContainer.addWidget(self.steamID_input)
        self.verticalLayout_2.addLayout(self.accountNameContainer)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.installedGames_tab = QtGui.QWidget()
        self.installedGames_tab.setObjectName("installedGames_tab")
        self.gridLayout_5 = QtGui.QGridLayout(self.installedGames_tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.installedGames_list = QtGui.QListWidget(self.installedGames_tab)
        self.installedGames_list.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.installedGames_list.setObjectName("installedGames_list")
        self.gridLayout_5.addWidget(self.installedGames_list, 0, 0, 1, 1)
        self.tabWidget.addTab(self.installedGames_tab, "")
        self.ownedGamesTab = QtGui.QWidget()
        self.ownedGamesTab.setObjectName("ownedGamesTab")
        self.gridLayout_4 = QtGui.QGridLayout(self.ownedGamesTab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.ownedGames_list = QtGui.QListWidget(self.ownedGamesTab)
        self.ownedGames_list.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.ownedGames_list.setObjectName("ownedGames_list")
        self.gridLayout_4.addWidget(self.ownedGames_list, 0, 0, 1, 1)
        self.tabWidget.addTab(self.ownedGamesTab, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.gameInfoContainer = QtGui.QHBoxLayout()
        self.gameInfoContainer.setObjectName("gameInfoContainer")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gameIcon_label = QtGui.QLabel(self.centralwidget)
        self.gameIcon_label.setMinimumSize(QtCore.QSize(32, 32))
        self.gameIcon_label.setText("")
        self.gameIcon_label.setObjectName("gameIcon_label")
        self.horizontalLayout.addWidget(self.gameIcon_label)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gameName_label = QtGui.QLabel(self.centralwidget)
        self.gameName_label.setText("")
        self.gameName_label.setObjectName("gameName_label")
        self.verticalLayout.addWidget(self.gameName_label)
        self.gameShortName_label = QtGui.QLabel(self.centralwidget)
        self.gameShortName_label.setText("")
        self.gameShortName_label.setObjectName("gameShortName_label")
        self.verticalLayout.addWidget(self.gameShortName_label)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gameInfoContainer.addLayout(self.horizontalLayout)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gameInfoContainer.addItem(spacerItem)
        self.selectAllButton = QtGui.QPushButton(self.centralwidget)
        self.selectAllButton.setObjectName("selectAllButton")
        self.gameInfoContainer.addWidget(self.selectAllButton)
        self.refreshButton = QtGui.QPushButton(self.centralwidget)
        self.refreshButton.setObjectName("refreshButton")
        self.gameInfoContainer.addWidget(self.refreshButton)
        self.installButton = QtGui.QPushButton(self.centralwidget)
        self.installButton.setObjectName("installButton")
        self.gameInfoContainer.addWidget(self.installButton)
        self.verticalLayout_2.addLayout(self.gameInfoContainer)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 527, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.generateDesuraReport_action = QtGui.QAction(MainWindow)
        self.generateDesuraReport_action.setObjectName("generateDesuraReport_action")
        self.refreshLists_action = QtGui.QAction(MainWindow)
        self.refreshLists_action.setObjectName("refreshLists_action")
        self.menuFile.addAction(self.generateDesuraReport_action)
        self.menuFile.addAction(self.refreshLists_action)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.desuraAccountName_input, QtCore.SIGNAL("returnPressed()"), self.desuraAccountName_verify.click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "DesuraTools", None, QtGui.QApplication.UnicodeUTF8))
        self.desuraAccountName_label.setText(QtGui.QApplication.translate("MainWindow", "Desura Profile ID", None, QtGui.QApplication.UnicodeUTF8))
        self.desuraAccountName_input.setText(QtGui.QApplication.translate("MainWindow", "Your Desura Profile ID", None, QtGui.QApplication.UnicodeUTF8))
        self.desuraAccountName_input.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Your Desura Username", None, QtGui.QApplication.UnicodeUTF8))
        self.desuraAccountName_verify.setText(QtGui.QApplication.translate("MainWindow", "Load Games", None, QtGui.QApplication.UnicodeUTF8))
        self.steamID_label.setText(QtGui.QApplication.translate("MainWindow", "Steam ID", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.installedGames_tab), QtGui.QApplication.translate("MainWindow", "Installed Desura Games", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ownedGamesTab), QtGui.QApplication.translate("MainWindow", "Owned Desura Games", None, QtGui.QApplication.UnicodeUTF8))
        self.selectAllButton.setText(QtGui.QApplication.translate("MainWindow", "Select All", None, QtGui.QApplication.UnicodeUTF8))
        self.refreshButton.setText(QtGui.QApplication.translate("MainWindow", "Refresh List", None, QtGui.QApplication.UnicodeUTF8))
        self.installButton.setText(QtGui.QApplication.translate("MainWindow", "Install Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.generateDesuraReport_action.setText(QtGui.QApplication.translate("MainWindow", "Generate Desura Report", None, QtGui.QApplication.UnicodeUTF8))
        self.refreshLists_action.setText(QtGui.QApplication.translate("MainWindow", "Refresh All Games", None, QtGui.QApplication.UnicodeUTF8))

